<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="RemoteMappingsManager">
    <list>
      <list>
        <remote-mappings server-id="python@sftp://ubuntu@210.45.212.238:22/home/ubuntu/anaconda3/envs/chen/bin/python3.6">
          <settings>
            <list>
              <mapping local-root="$PROJECT_DIR$" remote-root="/home/jhw/WA22301089/gravity_graph_autoencoders-master" />
            </list>
          </settings>
        </remote-mappings>
        <remote-mappings server-id="python@sftp://root@region-8.autodl.pro:39123/root/miniconda3/envs/Gravity-GAE/bin/python3.6">
          <settings>
            <list>
              <mapping local-root="$PROJECT_DIR$" remote-root="/root/autodl-tmp/gravity_graph_autoencoders-master" />
            </list>
          </settings>
        </remote-mappings>
        <remote-mappings server-id="python@sftp://jhw@210.45.212.238:22/home/ubuntu/anaconda3/envs/chen/bin/python3.6">
          <settings>
            <list>
              <mapping local-root="$PROJECT_DIR$" remote-root="/media/ubuntu/disk_0/jhw/WA22301089/gravity_graph_autoencoders-master" />
            </list>
          </settings>
        </remote-mappings>
        <remote-mappings server-id="python@sftp://jhw@210.45.212.238:22/home/anaconda3/envs/chen/bin/python3.6">
          <settings>
            <list>
              <mapping local-root="$PROJECT_DIR$" remote-root="/home/jhw/WA22301089/gravity_graph_autoencoders-master" />
            </list>
          </settings>
        </remote-mappings>
      </list>
    </list>
  </component>
</project>